### ISSUE TITLE
Improving the documentation regarding how the state is persisted

### ISSUE THREAD

**Issue by zrfrank** [felangel/hydrated_bloc#12]
It would be great if the documentation can explain a bit more about:

- how, the state is persisted, for example, is it a database or a simple json file
- where, is the persisted file saved
- is it fast to persist, or should be used wisely
- safety advice regarding persisted state (i.e. whether it is safe to persist user related infos)
- is the persisted file can be encrypted

**Comment by felangel** [comment]
Addressed questions in https://github.com/felangel/hydrated_bloc/commit/8cae779a421cbf17a60207bc23d074e3ef67be6d.
