### ISSUE TITLE
Support saving bloc's state instead of The state that bloc produces.

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [felangel/hydrated_bloc#13]
**Is your feature request related to a problem? Please describe.**
I have a repositoryBloc that caches results. When using HydratedBloc, I can only store the output of the bloc, not it's internal private state.
**Describe the solution you'd like**
Don't require the fromJson method of `HydratedBloc<E, S>` to be of type `S`
**Describe alternatives you've considered**
I've considered customizing the output of toJson and fromJson, but it seems complicated and probably impossible.
An alternative is to allow for persisting extra bloc data.

**Comment by felangel** [comment]
Hey @ThinkDigitalSoftware 👋 
Thanks for opening an issue!

Can you provide a bit more info around what the internal state of the bloc is and why it’s needed?

Thanks!

**Comment by ThinkDigitalSoftware** [comment]
Sure, say I have the following `HydratedBloc`:

```dart
class PackageDetailsBloc extends HydratedBloc<PackageDetailsEvent, PackageDetailsState> {
Map _cache = {};
  @override
  PackageDetailsState get initialState => InitialPackageDetailsState();

  @override
  Stream<PackageDetailsState> mapEventToState(
    PackageDetailsEvent event,
  ) async* {
    if(event is GetItem){
    if(_cache.containsKey(event.item)) return _cache[item]
    else {
        var item =  await getItemFromRepo();
        _cache[item] = item;
        yield item;
        return;
    }
  }
}
```

I'm interested in persisting the _cache variable. This is the real state of my bloc, and this is what I want to persist. I also want to persist `myBloc.currentState`, but I don't want to have to attach the _cache to that state just to be able to persist it

**Comment by felangel** [comment]
Hey @ThinkDigitalSoftware my goal with `HydratedBloc` was to automatically cache the state of the bloc so that your application can pickup where it left off. Why do you need to have an internal cache within the bloc? If your bloc state is cached you should not need to query the repo at all.

**Comment by ThinkDigitalSoftware** [comment]
The cache is for previous queries. If a query hasn't been run, it uses the
repo. I could renew the cache each time the app is run, but I do feel like
blocs should be able to serialize and rehydrate themselves, not just the
state they produce. Who knows what other use cases there are for this

**Comment by ThinkDigitalSoftware** [comment]
If a person died and you wanted to recreate them, it wouldn't be enough to just save the work they did, you'd need to save other properties about them that made them who they were. Their Metadata. I think this should be the same way

**Comment by felangel** [comment]
@ThinkDigitalSoftware can you please provide a concrete use case that we can walk through? I think it would be a lot easier to reference a specific example.

**Comment by ThinkDigitalSoftware** [comment]
Ok. Something more than the example above?

**Comment by felangel** [comment]
Well with the example above I’d move the cache to the repository layer. That way the bloc just requests the data and doesn’t care about where the data is coming from but if you can provide a concrete use case for an actual feature you’re working on I think it’d be more beneficial to compare and contrast approaches.

**Comment by ThinkDigitalSoftware** [comment]
This is a part of the pub project I'm working on. This bloc is my repo,
isn't it?

**Comment by felangel** [comment]
What do you mean the bloc is your repo? Ideally you'd have a data provider (in your case the pub.dev api client), a repository to interface with the data provider and convert the raw data model into your business models, a bloc to interface with your repository and provide the state/view model for your feature, and your UI to consume your bloc's state (view model) and render in response to different states.

hydrated_bloc helps to cache your feature state so that your application picks up in the state it was last in (without having to reinitialize and fetch the initial data set while presenting loading indicators etc...).

If you wanted a cache for your data it would be best to put the cache in the repository layer because that's the layer that directly interfaces with the data provider. You can check out the [github search](https://github.com/felangel/bloc/blob/master/examples/github_search/common_github_search/lib/src/github_repository.dart) app for an example.

**Comment by ThinkDigitalSoftware** [comment]
Ok. I have this repository class you linked to as part of the bloc itself. Implemented the same way you have it there. So I'll need to find a different way to persist this repository's cache to the device..  [Source ](https://github.com/ThinkDigitalSoftware/tavern/blob/transition-to-bloc/lib/screens/package_details/package_details_bloc.dart)

**Comment by felangel** [comment]
I would highly recommend decoupling the bloc from the repository.
You can write to file, use a db, etc... for the repository cache.

Did this help clarify things?

**Comment by ThinkDigitalSoftware** [comment]
It's clear, yes. It just defeats my purpose in using HydratedBloc now, since the rest of the state is so light that it won't save me much processing. I'm sure it'll be more helpful for larger projects. I was implementing HydratedBloc to keep from having to spin my own persistence solution, but it seems like your suggestion **is** to spin my own persistence solution?

**Comment by felangel** [comment]
No my suggestion is to not store internal state in the bloc. You can add your own solution if you want to the repository layer but it isn’t necessary if you refactor your bloc. Which bloc is this in the pub.dev client? I can take a look and try to create a PR with my suggestions.

**Comment by ThinkDigitalSoftware** [comment]
I sent you a PR to review. I refactored it out of the bloc into its own
class, it's in the Search bloc, the home bloc and the package details bloc
