### ISSUE TITLE
Question: persistence time

### ISSUE THREAD

**Issue by pblinux** [felangel/hydrated_bloc#14]
Hi. First, awesome work with hydrated too.

I have a question/issue :thinking:

I'm using hydrated to store if it isn't the first time the app is opening. It works but after some time, like 4 o 5 days, the state is lost.

I'm using hydrated incorrectly?

```
class MainBloc extends HydratedBloc<MainEvent, MainState> {
  @override
  MainState get initialState =>
      super.initialState ?? MainState(true, false);

  @override
  Stream<MainState> mapEventToState(
    MainEvent event,
  ) async* {
    if (event is DisableFirstTime) {
      yield MainState(false, currentState.logged);
    }
  }

  void dispatchDisableFirstTime() {
    dispatch(DisableFirstTime());
  }

  @override
  MainState fromJson(Map<String, dynamic> json) =>
      MainState(json['firstTime'] as bool, json['logged'] as bool);

  @override
  Map<String, dynamic> toJson(MainState state) =>
      {'firstTime': state.firstTime, 'logged': state.logged};
}

class MainState {
  bool firstTime;
  bool logged;

  MainState(this.firstTime, this.logged);
}

class DisableFirstTime extends MainEvent {
  @override
  String toString() => 'DisableFirstTime';
}

```

Thank you for your time.

**Comment by felangel** [comment]
Hi @pblinux 👋 
Thanks for opening an issue and for the positive feedback!

Regarding your question, out-of-the-box `HydratedBlocStorage` writes to [temporary storage](https://github.com/flutter/plugins/blob/61c39d1e79e8f36030162a5f85fb491c65f4e51c/packages/path_provider/lib/path_provider.dart#L24).

```sh
/// Path to the temporary directory on the device that is not backed up and is
/// suitable for storing caches of downloaded files.
///
/// Files in this directory may be cleared at any time. This does *not* return
/// a new temporary directory. Instead, the caller is responsible for creating
/// (and cleaning up) files or directories within this directory. This
/// directory is scoped to the calling application.
///
/// On iOS, this uses the `NSCachesDirectory` API.
///
/// On Android, this uses the `getCacheDir` API on the context.
```

If that doesn't meet your needs, you can always implement your own `HydratedStorage` by simply implementing the `HydratedStorage` interface and initializing `HydratedBlocDelegate` with your custom `HydratedStorage`.

```dart
// my_hydrated_storage.dart

class MyHydratedStorage implements HydratedStorage {
  @override
  dynamic read(String key) {
    // TODO: implement read
  }

  @override
  Future<void> write(String key, dynamic value) async {
    // TODO: implement write
  }

  @override
  Future<void> clear() async {
    // TODO: implement clear
  }
}
```

```dart
// my_hydrated_bloc_delegate.dart

class MyHydratedBlocDelegate extends HydratedBlocDelegate {
 MyHydratedBlocDelegate() : super(MyHydratedBlocStorage());
}
```

```dart
// main.dart

BlocSupervisor.delegate = MyHydratedBlocDelegate();
```

Hope that helps 👍

**Comment by pblinux** [comment]
Thank you @felangel , that gets me more clear idea of what can I do. Again, thank you.

**Comment by shamnex** [comment]
Quick question? Is it possible to have multiple **HydratedStorage**?  
I want to use the default storage for all my HydratedBlocs, then use my own custom **HydratedStorage** for only one.

Thanks for all the great works @felangel !!

**Comment by felangel** [comment]
@shamnex you'll have to write your own `HydratedBlocDelegate` for that. Can you provide more details around your use-case? I wouldn't recommend having logic for where to store bloc states. Instead, if you have data that needs to be persisted in a different location you should probably handle that outside of hydrated_bloc. Hope that helps 👍

**Comment by shamnex** [comment]
Thanks for the quick reply! Yup, that helps. 

Here's my use-case, 
 I want to persist my App Settings with a custom hydrated Storage and I wrote (using the Sembast plugin), as I don't want this to be deleted when I'm not aware of it.

 I also have data that changes frequently (Timeline feed) that only the last loaded data needs to be cached (perfect with Hydrated Bloc).

Do u still reckon I move the login outside the bloc for my settings ? or just use the custom Hydrated Storage for all the data? 

Thanks once again!

**Comment by felangel** [comment]
No problem!

It might be best to just use the custom HydratedStorage for everything. Alternatively, you can just use Sembast for the app settings explicitly and keep the AppSettingsBloc as a regular bloc.

I would personally probably use the custom HydratedStorage for everything unless you're running into performance problems 👍

**Comment by shamnex** [comment]
Alright man! Cheers

**Comment by shamnex** [comment]
Good morning, I'm here again to disturb you again :(.

I just noticed Sembast read operations are asynchronous and it makes it impossible for me to get my cached data when I call super.initialState() in my `hydratedBloc`;

It throws `type 'Future<dynamic>' is not a subtype of type 'String'`.

How would you approach this?

**Comment by kakajansh** [comment]
@felangel is it possible to create custom **HydratedStorage**, and make it write to `getApplicationDocumentsDirectory()` instead of `getTemporaryDirectory()`. Will it persist data, and avoid clearing by OS?

**Comment by felangel** [comment]
@shamnex hey 👋 

Would it be feasible for you to perform an initial asynchronous query in the initialization of the storage client which would read everything into memory? You would then be able to synchronously return values for a given key. It would be very similar to how the built-in `HydratedBlocStorage` works.

```dart
void main() async {
  BlocSupervisor.delegate = await HydratedBlocDelegate.build();
  runApp(App());
}
```

`HydratedBlocDelegate.build();` handles load the data asynchronously into memory.

Let me know if that helps or if it doesn't meet your requirements 👍

**Comment by felangel** [comment]
Hi @kakajansh 👋 
You definitely can but I would be cautious because in the documentation for `getApplicationDocumentsDirectory` it states:

> Path to a directory where the application may place data that is user-generated, or that cannot otherwise be recreated by your application.

Using `getApplicationDocumentsDirectory` for app cache is technically not what it is intended for.

**Comment by shamnex** [comment]
> @shamnex hey 👋
> 
> Would it be feasible for you to perform an initial asynchronous query in the initialization of the storage client which would read everything into memory? You would then be able to synchronously return values for a given key. It would be very similar to how the built-in `HydratedBlocStorage` works.
> 
> ```dart
> void main() async {
>   BlocSupervisor.delegate = await HydratedBlocDelegate.build();
>   runApp(App());
> }
> ```
> 
> `HydratedBlocDelegate.build();` handles load the data asynchronously into memory.
> 
> Let me know if that helps or if it doesn't meet your requirements 👍

Hello, champ!!! @felangel 

I just implemented it the way you asked and It works perfectly!

Thank you so much for this and keep up the good work.
It takes a lot to maintain an open source project with the level of commitment you show and also with a full-time job. We appreciate all your efforts man. 

Have a lovely weekend.
