### ISSUE TITLE
ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [felangel/hydrated_bloc#17]
hydrated_bloc version: v1.4.1

**Describe the bug**

>   Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
>  If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
>  If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
> defaultBinaryMessenger.<anonymous closure> (binary_messenger.dart:73)
> defaultBinaryMessenger (binary_messenger.dart:86)
> MethodChannel.binaryMessenger (platform_channel.dart:140)
> MethodChannel.invokeMethod (platform_channel.dart:314)
> <asynchronous gap>
> getTemporaryDirectory (path_provider.dart:26)
> <asynchronous gap>
> HydratedBlocStorage.getInstance (hydrated_bloc_storage.dart:34)
> <asynchronous gap>
> HydratedBlocDelegate.build (hydrated_bloc_delegate.dart:19)
> <asynchronous gap>
> main (main.dart:18)
> <asynchronous gap>
> main (main.dart:1)
> ...
> 

**To Reproduce**
Assuming here: Issue was caused after the update to Flutter 1.10.1, so update?

Paste the output of running `flutter doctor -v` here.
Flutter 1.10.1 • channel dev • https://github.com/flutter/flutter.git
Framework • revision ce45c2d3e6 (5 days ago) • 2019-09-06 20:11:41 -0400
Engine • revision b9ce2500d9
Tools • Dart 2.5.0 (build 2.5.0-dev.4.0 be66176534)

**Additional context**
My main() code is:
```dart
Future main() async {
  BlocSupervisor.delegate = await HydratedBlocDelegate.build();
```

**Comment by ThinkDigitalSoftware** [comment]
Wait, I'm using a forked version of hydrated_bloc. Most likely outdated

**Comment by felangel** [comment]
Hi @ThinkDigitalSoftware 👋 
Thanks for opening an issue!

Recent changes in Flutter require you to call `WidgetsFlutterBinding.ensureInitialized();` before using any plugins if the code is executed before `runApp`.

You should modify your main like so:

```dart
main() async {
  WidgetsFlutterBinding.ensureInitialized();
  BlocSupervisor.delegate = await HydratedBlocDelegate.build();

  ...
}
```

**Comment by ThinkDigitalSoftware** [comment]
Ok, cool. It didn't reflect in the docs as I was checking it compared with
the example

**Comment by felangel** [comment]
I’ll update the docs and example 👍

**Comment by gtxgat** [comment]
Thanks you. is it important to use this line  ` WidgetsFlutterBinding.ensureInitialized();` with flutter_bloc
for any app? or just when I using flutter_bloc for firebase sign-in.

**Comment by felangel** [comment]
@gtxgat no problem! You only need to call WidgetsFlutterBinding.ensureInitialized() in your main if you are using any plugins (like FirebaseAuth) before runApp is called.
