### ISSUE TITLE
[Feature Request] Add HydratedBloc.clear()

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [felangel/hydrated_bloc#21]
Since this operates as a sort of cache, caches have a clear/invalidate option.
I have some data I need to remove and the only way is to uninstall, or try to create a new empty state and yield it in order to do so

**Comment by felangel** [comment]
Hey @ThinkDigitalSoftware 👋 
Thanks for opening an issue!

Do you have a proposal for the API?

**Comment by ThinkDigitalSoftware** [comment]
Not really. Just that the call would be HydratedBloc.clearCache() or maybe HydratedBloc.reset() <-- maybe this can reset the state to initialState? Just some suggestions.

**Comment by felangel** [comment]
Done in #23 and released in hydrated_bloc v0.6.0 👍
