### ISSUE TITLE
Question: OnTransition and onError for HydratedBloc

### ISSUE THREAD

**Issue by Peter-717** [felangel/hydrated_bloc#3]
First of all, many thanks for your Bloc library, that's simply amazing!!!

Here is my issue:
I am adding HydratedBloc(s) to a project that does already contain many "SimpleBloc" that do not need to get Hydrated. So far I have been able to get the two sort of Blocs to co-exist with the following code:

void main() async {
  BlocSupervisor.delegate = SimpleBlocDelegate();
  BlocSupervisor.delegate = await HydratedBlocDelegate.build();
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
      .then((_) {
    runApp(new App());
  });
}

For the "SimpleBloc", I use the following to get the Transition and Error:
class SimpleBlocDelegate extends BlocDelegate {
  @override
  onTransition(Bloc bloc, Transition transition) {
    super.onTransition(bloc, transition);
  }

  @override
  void onError(Bloc bloc, Object error, StackTrace stacktrace) {
    super.onError(bloc, error, stacktrace);
  }
}

How do I achieve the same transition and error overrides for the HydratedBloc(s)?

Thanks again,

**Comment by felangel** [comment]
Hi @Peter-717 👋 
Thanks for opening an issue!

You can just tweak your `SimpleBlocDelegate` to extend `HydratedBlocDelegate` rather than `BlocDelegate` like so:

```dart
class SimpleBlocDelegate extends HydratedBlocDelegate {
  SimpleBlocDelegate(HydratedStorage storage) : super(storage);

  @override
  void onEvent(Bloc bloc, Object event) {
    super.onEvent(bloc, event);
    print(event);
  }

  @override
  void onError(Bloc bloc, Object error, StackTrace stacktrace) {
    super.onError(bloc, error, stacktrace);
    print(error);
  }

  @override
  void onTransition(Bloc bloc, Transition transition) {
    super.onTransition(bloc, transition);
    print(transition);
  }
}
```

Then you can use it like so:

```dart
BlocSupervisor.delegate =
      SimpleBlocDelegate(await HydratedBlocStorage.getInstance());
```

Hope that helps and great question! 👍

**Comment by Peter-717** [comment]
Works like a charm! Thank you so much!
