### ISSUE TITLE
Can't use HydratedBloc on non-Flutter platforms?

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [felangel/hydrated_bloc#30]
**Describe the bug**
Because of it's dependency on path_provider, the app fails on web and desktop (macOS in my case)
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>                                               
#1      getTemporaryDirectory (package:path_provider/path_provider.dart:35:22)
<asynchronous suspension>                                               
#2      HydratedBlocStorage.getInstance (package:hydrated_bloc/src/hydrated_bloc_storage.dart:39:49)
<asynchronous suspension>                                               
#3      HydratedBlocDelegate.build (package:hydrated_bloc/src/hydrated_bloc_delegate.dart:26:33)
<asynchronous suspension>                                               
#4      main (package:tavern/main.dart:21:56)                           
```

**To Reproduce**
1. Attempt to use HydratedBloc on web or desktop
2. See error

**Expected behavior**
Either have a check for the platform and use a platform io solution, or provide an alternative storage option for the dev to implement.

**Logs **
Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

Paste the output of running `flutter doctor -v` here.

> ➜  ~ flutter doctor -v   
> [✓] Flutter (Channel master, v1.12.1-pre.59, on Mac OS X 10.15.2 19C39d, locale en-US)
>     • Flutter version 1.12.1-pre.59 at /Users/thinkdigital/development/flutter
>     • Framework revision 6cb6857f92 (4 days ago), 2019-11-14 16:50:17 -0500
>     • Engine revision 77c3512ec8
>     • Dart version 2.7.0
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/thinkdigital/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • ANDROID_SDK_ROOT = /Users/thinkdigital/Library/Android/sdk
>     • Java binary at: /Users/thinkdigital/Library/Application
>       Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.2)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.2, Build version 11B44
>     • CocoaPods version 1.8.4
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 41.1.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Users/thinkdigital/Library/Application
>       Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832/Android Studio.app/Contents
>     • Flutter plugin version 41.1.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] IntelliJ IDEA Community Edition (version 2019.2.4)
>     • IntelliJ at /Applications/IntelliJ IDEA CE.app
>     • Flutter plugin version 41.1.4
>     • Dart plugin version 192.7402
> 
> [✓] VS Code (version 1.40.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.6.0
> 
> [✓] Connected device (5 available)
>     • SM G975U          • R58M23BRC7J                          • android-arm64  • Android 9 (API
>       28)
>     • iPhone 11 Pro Max • F3A5BA32-2FC7-491B-9862-A42B54C487A5 • ios            •
>       com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
>     • macOS             • macOS                                • darwin-x64     • Mac OS X 10.15.2
>       19C39d
>     • Chrome            • chrome                               • web-javascript • Google Chrome
>       78.0.3904.97
>     • Web Server        • web-server                           • web-javascript • Flutter Tools
> 

**Additional context**

**Comment by ThinkDigitalSoftware** [comment]
This may be related to #28. Checking that out now

**Comment by ThinkDigitalSoftware** [comment]
Already a feature with the  `HydratedStorage` option

**Comment by felangel** [comment]
@ThinkDigitalSoftware as you mentioned you can provide your own `HydratedStorage` but you can also just use it for desktop out of the box by including [path_provider_fde](https://github.com/google/flutter-desktop-embedding/tree/master/plugins/flutter_plugins/path_provider_fde) in your `pubspec.yaml`. Check out the [example](https://github.com/felangel/hydrated_bloc/blob/master/example/pubspec.yaml).
