### ISSUE TITLE
Set expiry date or ttyl

### ISSUE THREAD

**Issue by Sadmansamee** [felangel/hydrated_bloc#32]
Is it possible to set expiry date anyhow? Let's say on toJson set a expiry date and on toJson I will check if date is expired or not, if expired then fetch from API

**Comment by felangel** [comment]
Hey @Sadmansamee 👋 
Thanks for opening an issue!

Can you please provide some more context around the use case you have? You should always be able to include a `DateTime` in the data itself and wipe it if it's expired. Thanks!

**Comment by felangel** [comment]
@Sadmansamee any updates on this?
