### ISSUE TITLE
Question: How to enable onEvent, onError and onTransition logging?

### ISSUE THREAD

**Issue by wkrause13** [felangel/hydrated_bloc#33]
Is there a simple way to enable the onEvent, onError and onTransition logging found in many of the flutter_bloc tutorials?

I'm struggling to extend the HydratedBlocDelegate class without implementing the HydratedStorage interface.

**Comment by felangel** [comment]
Hi @wkrause13 👋 
Thanks for opening an issue!

Please take a look at https://github.com/felangel/hydrated_bloc/issues/3#issuecomment-505087002 and let me know if you have any further questions.
