### ISSUE TITLE
Hydrated Bloc yields the error state 

### ISSUE THREAD

**Issue by iampato** [felangel/hydrated_bloc#34]
**Describe the bug**
So i switched from flutterbloc to hydaretdbloc, when i my switch on the data connection and  i do not have an active internet connection the hydrated bloc works but when i complete shutdown the WiFi & the data connection it does not work

**Expected behavior**
Load the cached rest data rather than yielding the error state

**Comment by felangel** [comment]
Hi @Iampato 👋
Thanks for opening an issue!

Can you please share the link to a sample app which illustrates the problem you’re having? Thanks!

**Comment by iampato** [comment]
Can i just add you to the repo since its private

**Comment by felangel** [comment]
@Iampato sure 👍

**Comment by felangel** [comment]
@Iampato It doesn't look like you're using `hydrated_bloc` in the repo. Have you pushed your changes to a branch?

**Comment by iampato** [comment]
Wooh i forgot i just push

**Comment by felangel** [comment]
Sorry just saw this now! Will take a look ASAP 👍

**Comment by felangel** [comment]
@Iampato can you please reopen this issue in https://github.com/felangel/bloc if you're still having trouble. I realize this is quite an old issue and the hydrated_bloc repository has been merged into the core bloc repository 👍
