### ISSUE TITLE
How Persist a List

### ISSUE THREAD

**Issue by iCueto** [felangel/hydrated_bloc#4]
Hello, thank for you awesome plugin.

I want to persist a list, but I don't find how, the example only work for on item, and I am loss How to persist the different type of data.

Is it compatible with ```List<dynamic>```?

Thanks

**Comment by felangel** [comment]
Hi @iCueto 👋 
Thanks for opening an issue and for the positive feedback!

Can you provide some code snippets that illustrate what you want to do and what errors you’re getting? Thanks! 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional details and I'm happy to continue the conversation 👍
