### ISSUE TITLE
Need to update Path_provider dependency to support MacOS

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [felangel/hydrated_bloc#40]
latest version is   path_provider: ^1.6.5

**Comment by orsenkucher** [comment]
@felangel should we pull it with #38?

**Comment by felangel** [comment]
@orsenkucher id rather do it after since there are already significant changes. Once we merge #38 it will be trivial to upgrade path_provider but we need to verify that everything is still working properly.

**Comment by orsenkucher** [comment]
I don't see bold **Breaking Changes** in Changelog, tests passed
Should be ok to upgrade👍

**Comment by felangel** [comment]
@orsenkucher that's great but from an issue tracking perspective I'd prefer to have one PR per issue.

**Comment by orsenkucher** [comment]
Yes, NP. I have reverted things

**Comment by felangel** [comment]
@ThinkDigitalSoftware this change is available in [v3.1.0-dev.2](https://pub.dev/packages/hydrated_bloc/versions/3.1.0-dev.2) and will be included in v3.1.0 shortly 👍
