### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by Neriking69** [felangel/hydrated_bloc#44]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Neriking69** [comment]
I have no audio period, the bottom speaker went out 1st, now I have zero out on sound , only in blue tooth. Can someone please give me advice or fix .

**Comment by felangel** [comment]
Hi @Neriking69 👋 
Thanks for opening an issue!

Closing this since it doesn't sound like this is an issue with `hydrated_bloc` since the package has nothing to do with audio.
