### ISSUE TITLE
Tercera fase de desarrollo

### ISSUE THREAD

**Issue by EnriqueMenaGarcia** [felangel/hydrated_bloc#47]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs **
Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

Paste the output of running `flutter doctor -v` here.

**Additional context**

**Comment by felangel** [comment]
Closing this since there is no description.
