### ISSUE TITLE
Upgrade to bloc ^4.0.0

### ISSUE THREAD

**Issue by ali-alizadeh** [felangel/hydrated_bloc#48]
Hello
Do you have any plans on upgrading bloc package to the new released version?

**Comment by felangel** [comment]
Hi @Ali-Alizadeh 👋
Thanks for opening an issue!

Yup there are some other changes planned for hydrated bloc (in addition to the upgrade to bloc 4.0.0) so you can hopefully expect v4.0.0 of hydrated bloc to be released sometime this weekend 🤞
