### ISSUE TITLE
Maintain multiple states of a hydrated bloc

### ISSUE THREAD

**Issue by RaimundWege** [felangel/hydrated_bloc#51]
**Is your feature request related to a problem? Please describe.**
I'm wondering if it is possible to maintain multiple states of a hydrated bloc e.g. for each user of an app. If one user is logged out and another one is logged in the second user shouldn't see the data of the first one and vice versa but both data should be persisted.

**Describe the solution you'd like**
I would prefer to switch the storage directory based on a known user id but I don't know if this is possible during runtime.

**Comment by felangel** [comment]
Hi @RaimundWege 👋
You can accomplish this by overriding the id property on your hydrated bloc to be the id of the user 👍

Hope that helps!

**Comment by RaimundWege** [comment]
Thank you! That's exactly what I was looking for :)
