### ISSUE TITLE
State is replicated in Hive file

### ISSUE THREAD

**Issue by tensor5** [felangel/hydrated_bloc#57]
**Describe the bug**
Each time a state transition happens a new copy of the state is appended to the Hive DB file `hydrated_box.hive` causing it to grow linearly in size.

**To Reproduce**
1. Run the example app in the `example` folder
2. Run `adb shell` in a terminal window
3. Inside the adb shell run the command `run-as com.example.example`
4. Run `ls -l cache/hydrated_box.hive`
5. Press the plus button in the app
6. Run `ls -l cache/hydrated_box.hive` again

**Expected behavior**
Size of `hydrated_box.hive` should be the same.

**Comment by orsenkucher** [comment]
I suspect this behaviour is related to Hive in general. It uses append only strategy to achieve high write speed, though time to time it should reorganize and compact saved files.

**Comment by orsenkucher** [comment]
Hive mentions it in [compaction](https://docs.hivedb.dev/#/advanced/compaction) docs @tensor5

**Comment by orsenkucher** [comment]
@felangel also shared some Bitcask [papers](https://riak.com/assets/bitcask-intro.pdf?source=post_page---------------------------) time ago, page 4 addresses this problem
@tensor5

**Comment by tensor5** [comment]
Thanks for your answer. Hive mention compacting the box before closing to improve startup time. Do you plan to add this feature?

**Comment by felangel** [comment]
Hi @tensor5 👋 
Thanks for opening an issue!

We should definitely consider compacting the box before closing 👍
I'll try to get to this soon 😄

**Comment by orsenkucher** [comment]
@felangel how to know when box is closing?

**Comment by felangel** [comment]
> @felangel how to know when box is closing?

That’s the part we’ll need to figure out haha 😂

**Comment by felangel** [comment]
moved to https://github.com/felangel/bloc/issues/1422
