### ISSUE TITLE
Having an async operation in hydrated initialState

### ISSUE THREAD

**Issue by mohammadne** [felangel/hydrated_bloc#63]
in my case I want to use this awesome package for localization.
for the first run of app , I have 2 option:
```
@freezed
abstract class InitialLocale with _$InitialLocale {
  const factory InitialLocale.systemLocale() = SystemLocale;
  const factory InitialLocale.preferedLocale(Locale locale) = PreferedLocale;
}
```

my problem is when user choose SystemLocale.
because in ```initialState``` , I have:
```
  @override
  LocalizationState get initialState =>
      super.initialState ??
      LocalizationState(
        initialLocale.when(
          // systemLocale: () => it should be an async operation from intl package
          preferedLocale: (locale) => locale,
        ),
      );
```

so what do you suggest about retrieving this async operation ?

**Comment by mohammadne** [comment]
any suggestion about what can I do ?

**Comment by felangel** [comment]
Hey @mohammadne 👋 
Thanks for opening an issue!

Your initialState cannot be async. You need to either inject the locale into the bloc

```dart
class LocalizationBloc extends HydratedBloc<LocalizationEvent, LocalizationState> {
  LocalizationBloc(this.locale);

  final Locale locale;

  @override
  LocalizationState get initialState => super.initialState ?? LocalizationState(locale);
}
```

Or you need to have a state like `LocalizationLoadInProgress` which represents the state while the locale is being fetched.

Hope that helps 👍
