### ISSUE TITLE
HydratedBloc.storage should be typed [Storage]

### ISSUE THREAD

**Issue by danielmahon** [felangel/hydrated_bloc#64]
According to the docs this should be type `Storage` so it can accept a custom storage class.
Also looks like `Storage` isn't being exposed by the package either.

v5 looks awesome though, thanks!

https://github.com/felangel/hydrated_bloc/blob/07261573db71cfdb3aa054099c167be9ecf5f109/lib/src/hydrated_bloc.dart#L27

https://github.com/felangel/hydrated_bloc/blob/07261573db71cfdb3aa054099c167be9ecf5f109/lib/hydrated_bloc.dart#L3

**Comment by felangel** [comment]
Hi @danielmahon 👋 
Thanks for opening an issue!

Sorry about that! `HydratedStorage` used to be the name of the interface and I must have missed renaming/exporting it 😅 
Will be merged and released in v5.0.1 shortly 👍
