### ISSUE TITLE
Asynchronous fromJson and toJson

### ISSUE THREAD

**Issue by saivarunr** [felangel/hydrated_bloc#70]
**Is your feature request related to a problem? Please describe.**
Greetings @felangel , hope you are healthy and safe. I would also like to thank you for the libraries you have provided to the community. I'm using bloc and hydrated bloc. I was thinking why not provide async support for both fromJson and toJson on the HydratedBloc (https://github.com/felangel/hydrated_bloc/blob/15eb68febd6ccd075d5858341c422bd34b80bde7/lib/src/hydrated_bloc.dart#L37)

**Describe the solution you'd like**
I have this use case where we have to perform compute, validate checksum and then consider the input from local cache for further processing. At first, glance looks like it is not possible to invoke async methods/functions inside fromJson. If it cannot be implemented due to the underlying API, how do you suggest I should handle this problem on my side?

**Comment by felangel** [comment]
migrated to https://github.com/felangel/bloc/issues/1420
