### ISSUE TITLE
Bloc lifecycle w/Hydrated_Bloc?

### ISSUE THREAD

**Issue by bobwiller** [felangel/hydrated_bloc#8]
In a bloc pre-Hydrated_Bloc you might have a lifecycle that looks like this:

Init\Load -> New State -> Change Value -> New State (etc)

in that Init\Load event, you might go fetch a locally stored value (using something like mmkv) and if it didn't exist there, go get it from a database or service.

The readme says that state is "automatically" persisted and restored.  But what is the trigger/when is toJson() and fromJson() called?  

In your init, how do know if a previous state was saved?

Sorry if I have missed this somewhere.
Thanks,
Bob

**Comment by felangel** [comment]
Hey @bobwiller 👋 
Thanks for opening an issue and great questions!

The state is recovered from cache when you call `super.initialState()` and on every state change (transition), the `HydratedBlocDelegate` will attempt to write the state to cache by calling the hydrated bloc's toJson method (If `toJson` returns null, no cache updates will be made).

Hope that helps 👍

**Comment by 7Kronos** [comment]
Hello ! Thanks for your great libs @felangel ! 👍

I have a question and maybe a suggestion.

During my app start, I have a splash page that I want to dismiss when :

- Bloc transistions to UserLoaded  / user has a token, navigate to home page
- Bloc transistions to UserUnauthenticated / user does not have token, navigate to onboarding page

UserBloc is an HydratedBloc. Problem is when the Bloc is loaded (w/ data found or not) no event or transition is triggered, so a BlocListener would not trigger any logic, for this instance, navigating to either onboarding or home screen.

Before hydrating my states I had an AppStarts with an UserUninitialized state to transition from.

Do you have an idea of how to implement this elegantly ?
What do you think about an option where we could specify a starting state before fromJson is called ?

`
  UserState get initialState {
    return super.initialStateWithStartState(UserUninitialized()) ?? UserUninitialized();
  }
`
