### ISSUE TITLE
FormatException: Unexpected end of input error

### ISSUE THREAD

**Issue by bobwiller** [felangel/hydrated_bloc#9]
Running into this error:

Exception has occurred.
FormatException (FormatException: Unexpected end of input (at character 1)

On this line:

`void main() async {
  
  BlocSupervisor.delegate = SimpleBlocDelegate(
    await HydratedBlocStorage.getInstance(),             <-----error throwing here
  );`

Any idea what might be causing this? 
Thanks,
Bob

**Comment by felangel** [comment]
Hey @bobwiller thanks for reporting this and for triaging it and suggesting a fix! The fix was just made in https://github.com/felangel/hydrated_bloc/pull/11 and included in hydrated_bloc v0.3.1. 🎉
